DELETE FROM sites;
ALTER TABLE sites AUTO_INCREMENT = 1;

DELETE FROM posts;
ALTER TABLE posts AUTO_INCREMENT = 1;

DELETE FROM threads;
ALTER TABLE threads AUTO_INCREMENT = 1;

DELETE FROM boards;
ALTER TABLE boards AUTO_INCREMENT = 1;

DELETE FROM users;
ALTER TABLE users AUTO_INCREMENT = 1;

DELETE FROM docs;
ALTER TABLE docs AUTO_INCREMENT = 1;

DELETE FROM guilds; 
ALTER TABLE guilds AUTO_INCREMENT = 1;


DELETE FROM cells;
ALTER TABLE cells AUTO_INCREMENT = 1;

DELETE FROM texts;
ALTER TABLE texts AUTO_INCREMENT = 1;

DELETE FROM images;
ALTER TABLE images AUTO_INCREMENT = 1;

