DROP TABLE IF EXISTS sites;

DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS threads;
DROP TABLE IF EXISTS boards;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS docs;
DROP TABLE IF EXISTS guilds;

DROP TABLE IF EXISTS cells;
DROP TABLE IF EXISTS texts;
DROP TABLE IF EXISTS images;

