#!/bin/bash
#
# DB のテーブルをすべてドロップする
#
DBUSER="$FWU_DBUSER"
DBNAME="$FWU_DBNAME"
BASEDIR=$(dirname "$0")

echo db-user: $DBUSER
echo db-name: $DBNAME

fwu-confirm "上記 DB のテーブルをすべて破棄します。本当に実行しますか？"
if [ $? -ne 0 ]; then
    exit 1
fi

mysql -u $DBUSER -p $DBNAME < $BASEDIR/../../database/fwu-droptabs.sql

