#!/bin/bash
#
# サイト名を設定する
#
DBUSER="$FWU_DBUSER"
DBNAME="$FWU_DBNAME"

echo db-user: $DBUSER
echo db-name: $DBNAME

mysql -u $DBUSER -p $DBNAME <<EOF

UPDATE configs SET site_name = "$1" WHERE id = 1;

EOF

