#!/bin/bash
#
# DBのテーブルを初期化する。
#
DBUSER="$FWU_DBUSER"
DBNAME="$FWU_DBNAME"

echo db-user:$DBUSER
echo db-name:$DBNAME

fwu-confirm "上記の DB を初期化します。テーブルは再構築されません。本当に実行しますか？"
if [ $? -ne 0 ]; then
    exit 0
fi

NOW=`date +%Y-%m-%d`

mysql -u $DBUSER -p $DBNAME < ../../database/fwu-initdb.sql

