#!/bin/bash
#
# DBのテーブルを初期化する。
#
DBUSER="$FWU_DBUSER"
DBNAME="$FWU_DBNAME"
BASEDIR=$(dirname "$0")

echo db-user:$DBUSER
echo db-name:$DBNAME

fwu-confirm "上記の DB のテーブルを再構築して初期化します。現在のテーブルは全て破棄されます。本当に実行しますか？"
if [ $? -ne 0 ]; then
    exit 0
fi

mysql -u $DBUSER -p $DBNAME <<EOF

`cat $BASEDIR/../../database/fwu-builddb.sql`
`cat $BASEDIR/../../database/fwu-initdb.sql`

EOF

